services:
  production:
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c 'yarn start'
  develop:
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c 'yarn dev'
  unit_tests:
    env_file:
      - .env
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c 'yarn test'
