services:
  develop:
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c 'yarn && yarn dev'
